# -*- coding: utf-8 -*-
"""ImageProcessor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNdEsEPotNsp8vY5uPC54u4TqkvI7kD-
"""

import easyocr
from PIL import Image
import pandas as pd
from textblob import TextBlob
import pytesseract

pytesseract.pytesseract.tesseract_cmd='/usr/bin/tesseract'
custom_config=r'--oem 3 --psm 6 -l eng'

def get_image_text(image_path):
  img=Image.open(image_path)
  text=pytesseract.image_to_string(img, config=custom_config)
  return text

def autocorrect(txt):
  correct_text=TextBlob(txt).correct()
  correct_text=str(correct_text)
  return correct_text


def image_processing(dataset, image_path):
  df=pd.read_csv(dataset)
  paths=list(df['Path'])
  texts=list(df['Text'])
  pages=list(df['PageNo'])
  lines=list(df['LineNo'])
  frames=list(df['FrameNo'])
  columns=list(df['Column'])
  print('Starting Image Processing')
  img_text=get_image_text(image_path)
  corrected_text=autocorrect(img_text)
  paths.append(image_path)
  texts.append(corrected_text)
  pages.append(None)
  lines.append(None)
  frames.append(None)
  columns.append(None)
  data={'Path':paths, 'PageNo':pages, 'FrameNo':frames, 'LineNo':lines, 'Column':columns, 'Text':texts}
  df=pd.DataFrame(data)
  df.to_csv(dataset, index=False)
  return df.tail()
