# -*- coding: utf-8 -*-
"""PDFProcessor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kC3HbLmMG9pmKTs3dJaC_rVewRRLJPgq
"""


import fitz
import pandas as pd
from textblob import TextBlob

def get_pdf_text(pdf_path):
  pdftext=[]
  pdf=fitz.open(pdf_path)
  for pageno in range(len(pdf)):
    page=pdf.load_page(pageno)
    text=page.get_text()
    pdftext.append(text)
  #print(pdftext)
  return pdftext



def create_pdf_text(textlist):
  return ' '.join(textlist)



def autocorrect(text):
  correct_text=TextBlob(text).correct()
  correct_text=str(correct_text)
  return correct_text

def processpdf(dataset, pdf_path):
  df=pd.read_csv(dataset)
  textlist=get_pdf_text(pdf_path)
  wholetext=create_pdf_text(textlist)
  corrected_text=autocorrect(wholetext)
  new_row={'Path':[pdf_path], 'Text':[corrected_text]}
  row=pd.DataFrame(new_row)
  df=pd.concat([df,row], axis=0)
  df.to_csv(dataset, index=False)
  return corrected_text
