# -*- coding: utf-8 -*-
"""TextProcessor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLMWbDS8eonkyELcX-fqQzAed2by00l2
"""

import pandas as pd
from textblob import TextBlob

def processText(dataset, textfile):
  df=pd.read_csv(dataset)
  allpaths=df['Path']
  alltexts=df['Text']
  with open(textfile,'r') as f:
    data=f.read()
  data=str(data)
  new_row={'Path':[textfile], 'Text':[str(data)]}
  row=pd.DataFrame(new_row)
  df=pd.concat([df, row], axis=0)
  df.to_csv(dataset, index=False)
  return data
